[package]
name = "mulgore_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
uuid = "1.11.0"
serde_derive = "1.0.215"
reqwest = { version = "0.12.9", features = ["json"] }